# Problem 1

In [1]:
import numpy as np

In [2]:
def matrix_power(A, n):
    A = np.array(A)
    if A.shape[0] != A.shape[1]:
        raise ValueError("Matrix must be square")
    if n < 0 or n % 1 != 0:
        raise ValueError("Power must be non-negative integer")
    if np.any(A < 0) or np.any(A > 1) or np.isnan(A).any():
        raise ValueError("Matrix elements must be between 0 and 1")
    if np.any(abs(np.sum(A, axis=1) - 1) > 1e-9):
        raise ValueError("Each row must sum to 1")
    

    if n == 0:
        return np.eye(A.shape[0])
    
    for i in range(1, n + 1):
        if i == 1:
            result = A
        else:
            result = np.round(np.dot(result, A), 6)
            #print(result)

    return result

In [3]:
print("Valid 2x2:")
matrix_power(np.array([[0.5, 0.5], [0.2, 0.8]]), 10)

Valid 2x2:


array([[0.285718, 0.714282],
       [0.285713, 0.714287]])

In [4]:
print("Valid 3x3 with n=0:")
matrix_power(np.array([[0.1, 0.6, 0.3], [0.4, 0.5, 0.1], [0.7, 0.2, 0.1]]), 0)

Valid 3x3 with n=0:


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
print("Invalid matrix:")
matrix_power(np.array([[0.1, 0.6, 0.3], [0.4, 0.5, 0.1]]), 2)

Invalid matrix:


ValueError: Matrix must be square

In [6]:
print("Large n:")
matrix_power(np.array([[0.1, 0.6, 0.3], [0.4, 0.5, 0.1], [0.7, 0.2, 0.1]]), 50)

Large n:


array([[0.346773, 0.48387 , 0.169354],
       [0.346773, 0.48387 , 0.169355],
       [0.346774, 0.483872, 0.169355]])

In [ ]:
### VSCode autofilled some of this, but I edited to prompt errors ###
while True:
    exit_r = False
    row_error = False
    dim = int(input("Enter matrix size (n x n) (positive integer): "))
    if dim == 'exit':
        break
    if dim <= 0 or dim % 1 != 0:
        print("Size must be a positive integer.")
        continue
    matrix = []
    for i in range(dim):
        row_input = input(f"Row {i+1}: Separate by Spaces")
        if row_input == 'exit':
            exit_r = True
            break
        if row_input.count(' ') != dim - 1:
            row_error = True
            print(f"Row must have exactly {dim} elements.")
            break
            
        row = [float(x) for x in row_input.split()]
        matrix.append(row)

    if row_error: # Couldn't figure out how to re-prompt for individual row
        continue
    if exit_r:
        break

    matrix = np.array(matrix)
    if np.any(matrix < 0) or np.any(matrix > 1) or np.isnan(matrix).any():
        print("Matrix elements must be between 0 and 1.")
        continue

    if np.any(abs(np.sum(matrix, axis=1) - 1) > 1e-9):
        print("Each row must sum to 1.")
        continue

    n = int(input("Enter power (non-negative integer): "))
    if n == 'exit':
        break
    if n < 0 or n % 1 != 0:
        print("Power must be a non-negative integer.")
        continue

    print(matrix_power(matrix, n))

[[0.33 0.34 0.33]
 [0.14 0.48 0.38]
 [0.12 0.36 0.52]]


ValueError: invalid literal for int() with base 10: ''

# Problem 2

In [18]:
N = 10

B = np.zeros((N+1, N+1))
B[0, 1] = 1 # Fix from typo
B[-1, -2] = 1 # Same here
for i in range(1, N):
    B[i, i - 1] = (i / N)**2
    B[i, i + 1] = ((N - i) / N)**2
    B[i, i] = 2 * (i / N) * ((N - i) / N)

print(B)

[[0.   1.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.01 0.18 0.81 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.04 0.32 0.64 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.09 0.42 0.49 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.16 0.48 0.36 0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.25 0.5  0.25 0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.36 0.48 0.16 0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.49 0.42 0.09 0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.64 0.32 0.04 0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.81 0.18 0.01]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   1.   0.  ]]


In [21]:
x0 = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
x5 = np.dot(x0, matrix_power(B, 5))
x10 = np.dot(x0, matrix_power(B, 10))
x15 = np.dot(x0, matrix_power(B, 15))
x20 = np.dot(x0, matrix_power(B, 20))
print(f"E[X_0]={sum(x0[i] * i for i in range(len(x0)))}\n")
print(f"E[X_5]={sum(x5[i] * i for i in range(len(x5)))}\n")
print(f"E[X_10]={sum(x10[i] * i for i in range(len(x10)))}\n")
print(f"E[X_15]={sum(x15[i] * i for i in range(len(x15)))}\n")
print(f"E[X_20]={sum(x20[i] * i for i in range(len(x20)))}\n")

E[X_0]=10

E[X_5]=6.638393

E[X_10]=5.536861000000001

E[X_15]=5.1759129999999995

E[X_20]=5.057628



In [35]:
print(np.linalg.eig(B)[0])

[ 1.    0.8   0.62  0.46  0.32  0.2   0.1   0.02 -0.1  -0.08 -0.04]


Per Claude, every probability transition matrix must have at least one eigenvalue equal to 1. The corresponding eigenvector is the stationary distribution of the system. The second largest eigenvalue in absolute value corresponds to the rate at which the system converges to its stationary distribution. If the value is close to 1, then the convergence will be slow. If it is small, then the convergence is fast. Additionally, if all but one of the eigenvalues are strictly less than 1, then the system is irreducible and aperiodic.

In [40]:
print(f"Stationary distribution (from eigenvector): \n {np.linalg.eig(B.T)[1][:,0] / np.sum(np.linalg.eig(B.T)[1][:,0])}") # Division is to normalize eigenvector so entries sum to 1

Stationary distribution (from eigenvector): 
 [5.41254411e-06 5.41254411e-04 1.09604018e-02 7.79406352e-02
 2.38693195e-01 3.43718201e-01 2.38693195e-01 7.79406352e-02
 1.09604018e-02 5.41254411e-04 5.41254411e-06]
