# Problem 1

In [4]:
import numpy as np

In [104]:
def matrix_power(A, n):
    A = np.array(A)
    if A.shape[0] != A.shape[1]:
        raise ValueError("Matrix must be square")
    if n < 0 or n % 1 != 0:
        raise ValueError("Power must be non-negative integer")
    if np.any(A < 0) or np.any(A > 1) or np.isnan(A).any():
        raise ValueError("Matrix elements must be between 0 and 1")
    if np.any(abs(np.sum(A, axis=1) - 1) > 1e-9):
        raise ValueError("Each row must sum to 1")
    

    if n == 0:
        return np.eye(A.shape[0])
    
    for i in range(1, n + 1):
        if i == 1:
            result = A
        else:
            result = np.round(np.dot(result, A), 6)
            #print(result)

    return result

In [72]:
matrix_power(np.array([[0.5, 0.5], [0.2, 0.8]]), 10)

array([[0.285718, 0.714282],
       [0.285713, 0.714287]])

In [81]:
matrix_power(np.array([[0.1, 0.6, 0.3], [0.4, 0.5, 0.1], [0.7, 0.2, 0.1]]), 0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [82]:
matrix_power(np.array([[0.1, 0.6, 0.3], [0.4, 0.5, 0.1]]), 2)

ValueError: Matrix must be square

In [84]:
matrix_power(np.array([[0.1, 0.6, 0.3], [0.4, 0.5, 0.1], [0.7, 0.2, 0.1]]), 50)

array([[0.346773, 0.48387 , 0.169354],
       [0.346773, 0.48387 , 0.169355],
       [0.346774, 0.483872, 0.169355]])

In [140]:
### Claude wrote this shortcut ###
while True:
    exit_r = False
    dim = int(input("Enter matrix size (n x n): "))
    if dim == 'exit':
        break
    matrix = []
    for i in range(dim):
        row_input = input(f"Row {i+1}: Separate by Spaces")
        if row_input == 'exit':
            exit_r = True
            break
        row = [float(x) for x in row_input.split()]
        matrix.append(row)
    if exit_r:
        break
    matrix = np.array(matrix)
    n = int(input("Enter power (non-negative integer): "))
    if n == 'exit':
        break

    print(matrix_power(matrix, n))

[[0.5 0.5]
 [0.5 0.5]]
[[0.5 0.5]
 [0.3 0.7]]
[[0.56 0.44]
 [0.55 0.45]]


ValueError: invalid literal for int() with base 10: 'exit'

# Problem 2

In [88]:
N = 10

B = np.zeros((N+1, N+1))
B[0, 0] = 1
B[-1, -1] = 1
for i in range(1, N):
    B[i, i - 1] = (i / N)**2
    B[i, i + 1] = ((N - i) / N)**2
    B[i, i] = 2 * (i / N) * ((N - i) / N)

print(B)

[[1.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.01 0.18 0.81 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.04 0.32 0.64 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.09 0.42 0.49 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.16 0.48 0.36 0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.25 0.5  0.25 0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.36 0.48 0.16 0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.49 0.42 0.09 0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.64 0.32 0.04 0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.81 0.18 0.01]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   1.  ]]


In [141]:
x0 = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
print(np.dot(x0, matrix_power(B, 5)))   # state 10 is absorbing?

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


In [117]:
print(np.linalg.eig(B)[0])

[ 0.99998932  0.79983897  0.61889687  0.4554567   0.30732701  0.17420289
 -0.08588908 -0.02949856  0.05967588  1.          1.        ]


Per Claude, every probability transition matrix must have at least one eigenvalue equal to 1. The corresponding eigenvector is the stationary distribution of the system. The second largest eigenvalue in absolute value corresponds to the rate at which the system converges to its stationary distribution. If the value is close to 1, then the convergence will be slow. If it is small, then the convergence is fast. Additionally, if all but one of the eigenvalues are strictly less than 1, then the system is irreducible and aperiodic.